spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=create-drop

auth.jwt.secret=X9f$7vL!pQz@3rT#bWm^2eK&uYh*6nJgZsLdCqAoEiTxV
auth.jwt.timeout=5m

logging.level.org.springframework.security=DEBUG