spring.application.name=caseworker-service

## H2 Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:caseworkerTestDB}
spring.datasource.driverClassName=${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.jpa.database-platform=${SPRING_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
spring.h2.console.enabled=true
# Automatically create tables based on JPA entities
spring.jpa.hibernate.ddl-auto=update
# Wait until after create schema before execute.
spring.jpa.defer-datasource-initialization=true

server.port=${SPRING_SERVER_PORT:8081}

jwt.security.key=${JWT_SECRET_KEY:X9f$7vL!pQz@3rT#bWm^2eK&uYh*6nJgZsLdCqAoEiTxV}
jwt.security.timeout=3000000

# SQL Logging Configuration
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
